# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Paul Daniel
title: Machine Learning Engineer
email: paudan22@gmail.com
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  PaulDanielML
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: paul-daniel-6b3646178
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Paul and I am a Machine Learning Engineer from Germany, currently living and working in Denmark. I am eager to apply my skill set in a field of high environmental impact. I love learning new things, pushing myself and am able to pick up new domain knowledge quickly.

  I am most skilled in: <mark>Deep Learning</mark> and <mark>Python</mark>

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: OYO
        link: https://www.oyorooms.com/
        link_text: oyorooms.com
        sub_title: Machine Learning Engineer
        caption: October 2020 - Present
        quote: >
          Researching, implementing, deploying & monitoring ML models for large user bases.
        description: | # this will include new lines to allow paragraphs
          Working as part of the Data Science team, here are some things I have been working on:
          - Deep Leaning, for Computer Vision as well as Tabular Data
          - Development and deployment of gradient-boosted ranking algorithms
          - Optimizing Python code for production
          - MLOps & Data Engineering

          Most relevant skills used:
          <mark>Python</mark>, <mark>Deep Learning</mark>, <mark>Machine Learning</mark>, <mark>SQL</mark>, <mark>Docker</mark>, <mark>GCP</mark>, <mark>PyTorch</mark>, <mark>Pandas</mark>, <mark>Airflow</mark>, <mark>FastAPI</mark>, <mark>Git</mark>
      
      - layout: left
        title: Aalborg University
        link: http://robotics-automation.aau.dk/
        link_text: robotics-automation.aau.dk
        sub_title: Guest Researcher
        caption: 2020
        quote: >
          Implementing and end-to-end Deep Reinforcement Learning system for robotic applications.
        description: | # this will include new lines to allow paragraphs
          As part of the Robotics & Automation research group I worked on investigating the use of Deep Reinforcement Learning to teach robots how to grasp objects withou prior knowledge. This involved:
          - Setting up a simulation environment 
          - Building a gym-environment using Python
          - Researching & implementing various RL algorithms in PyTorch
          
          Most relevant skills used:
          <mark>Python</mark>, <mark>Reinforcement Learning</mark>, <mark>Deep Learning</mark>, <mark>PyTorch</mark>, <mark>Simulation</mark>

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Mujoco RL UR5
        link: https://github.com/PaulDanielML/MuJoCo_RL_UR5
        link_text: github.com/PaulDanielML/MuJoCo_RL_UR5
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Deep Reinforcement Learning for robotic pick and place applications using purely visual observations
        description: | # this will include new lines to allow paragraphs
          This started out as the project of my Master's thesis, but due to its promising results, as well as high interest from many international researchers, was continued far beyond that.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Technical University of Berlin
        caption: 2017 - 2020
        sub_title: MSc Mech. Engineering
        # quote: >
          # Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          Focus: Artificial Intelligence systems and applications.

      - layout: left
        title: Technical University of Berlin
        caption: 2013 - 2017
        sub_title: BSc Mech. Engineering
        # quote: >
          # Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          Focus: Math, mechanics & dynamic systems.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in Machine Learning some of my other interests include:
      - Discovering, being in and conserving nature
      - Beachvolleyball
      - Music

    # Look at this cool image  
    # ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
